// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/acompanhamento": {
            "post": {
                "description": "Cria um acompanhamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "acompanhamento"
                ],
                "summary": "Cria um acompanhamento",
                "parameters": [
                    {
                        "description": "Acompanhamento",
                        "name": "acompanhamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.AcompanhamentoPedido"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/acompanhamento/{IDAcompanhamento}/pedido/{IDPedido}/status": {
            "put": {
                "description": "Atualiza o status de um pedido no acompanhamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "acompanhamento"
                ],
                "summary": "Atualiza o status de um pedido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do acompanhamento",
                        "name": "IDAcompanhamento",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do pedido",
                        "name": "IDPedido",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo status do pedido",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.StatusUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pedido ou acompanhamento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/acompanhamento/{IDAcompanhamento}/{IDPedido}": {
            "post": {
                "description": "Adiciona um pedido existente ao acompanhamento de pedidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "acompanhamento"
                ],
                "summary": "Adiciona um pedido ao acompanhamento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do acompanhamento",
                        "name": "IDAcompanhamento",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do pedido",
                        "name": "IDPedido",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pedido ou acompanhamento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/acompanhamento/{ID}": {
            "get": {
                "description": "Busca um acompanhamento pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "acompanhamento"
                ],
                "summary": "Busca um acompanhamento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do acompanhamento",
                        "name": "ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenters.AcompanhamentoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Acompanhamento não encontrado",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cliente": {
            "post": {
                "description": "Cria um cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cliente"
                ],
                "summary": "Cria um cliente",
                "parameters": [
                    {
                        "description": "Cliente",
                        "name": "cliente",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Cliente"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cliente/{CPF}": {
            "get": {
                "description": "Busca um cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cliente"
                ],
                "summary": "Busca um cliente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF do cliente",
                        "name": "CPF",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenters.ClienteDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pagamento": {
            "post": {
                "description": "Envia o pagamento para o webhook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pagamento"
                ],
                "summary": "Envia o pagamento para o webhook",
                "parameters": [
                    {
                        "description": "Pagamento",
                        "name": "pagamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Pagamento"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pagamento/confirmar": {
            "post": {
                "description": "Confirma o pagamento",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pagamento"
                ],
                "summary": "Confirma o pagamento",
                "parameters": [
                    {
                        "description": "Pagamento",
                        "name": "pagamento",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Pagamento"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pedidos": {
            "post": {
                "description": "Cria um pedido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pedido"
                ],
                "summary": "Cria um pedido",
                "parameters": [
                    {
                        "description": "Pedido",
                        "name": "pedido",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Pedido"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pedidos/listartodos": {
            "post": {
                "description": "Lista todos os pedidos presentes no banco",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pedido"
                ],
                "summary": "Lista todos os pedidos no banco",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Pedido"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pedidos/{ID}": {
            "get": {
                "description": "Busca um pedido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pedido"
                ],
                "summary": "Busca um pedido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número do pedido",
                        "name": "ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Pedido"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pedidos/{nroPedido}/status/{status}": {
            "put": {
                "description": "Atualizar um pedido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pedido"
                ],
                "summary": "Atualiza um pedido a partir de sua Identificação",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Número do pedido",
                        "name": "nroPedido",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Novo Status do pedido",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Pedido"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produto": {
            "post": {
                "description": "Cria um produto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produto"
                ],
                "summary": "Cria um produto",
                "parameters": [
                    {
                        "description": "Produto",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Produto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produto/{id}": {
            "get": {
                "description": "Busca um produto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produto"
                ],
                "summary": "Busca um produto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenters.ProdutoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produto/{nome}": {
            "delete": {
                "description": "Remove um produto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produto"
                ],
                "summary": "Remove um produto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nome do produto",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos": {
            "get": {
                "description": "Lista todos os produtos cadastrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produto"
                ],
                "summary": "Lista todos os produtos no banco",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Produto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita um produto existente pelo nome",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produto"
                ],
                "summary": "Edita um produto",
                "parameters": [
                    {
                        "description": "Produto",
                        "name": "produto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Produto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/produtos/{categoria}": {
            "get": {
                "description": "Lista todos os produtos por categoria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produto"
                ],
                "summary": "Lista os produtos por categoria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Categoria de produtos",
                        "name": "categoria",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Produto"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.AcompanhamentoPedido": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "pedidos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Pedido"
                    }
                },
                "tempoEstimado": {
                    "type": "string"
                },
                "ultimaAtualizacao": {
                    "type": "string"
                }
            }
        },
        "entities.CatProduto": {
            "type": "string",
            "enum": [
                "Lanche",
                "Acompanhamento",
                "Bebida",
                "Sobremesa"
            ],
            "x-enum-varnames": [
                "Lanche",
                "Acompanhamento",
                "Bebida",
                "Sobremesa"
            ]
        },
        "entities.Cliente": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "entities.Pagamento": {
            "type": "object",
            "properties": {
                "dataCriacao": {
                    "type": "string"
                },
                "idPagamento": {
                    "type": "integer"
                },
                "idPedido": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "entities.Pedido": {
            "type": "object",
            "properties": {
                "cliente_cpf": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "produtos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Produto"
                    }
                },
                "status": {
                    "$ref": "#/definitions/entities.StatusPedido"
                },
                "status_pagamento": {
                    "type": "string"
                },
                "time_stamp": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                },
                "ultima_atualizacao": {
                    "type": "string"
                }
            }
        },
        "entities.Produto": {
            "type": "object",
            "properties": {
                "categoriaProduto": {
                    "$ref": "#/definitions/entities.CatProduto"
                },
                "descricaoProduto": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nomeProduto": {
                    "type": "string"
                },
                "personalizacaoProduto": {
                    "$ref": "#/definitions/sql.NullString"
                },
                "precoProduto": {
                    "type": "number"
                }
            }
        },
        "entities.StatusPedido": {
            "type": "string",
            "enum": [
                "Pendente",
                "Recebido",
                "Em preparação",
                "Pronto",
                "Finalizado"
            ],
            "x-enum-varnames": [
                "Pendente",
                "Recebido",
                "EmPreparacao",
                "Pronto",
                "Finalizado"
            ]
        },
        "handler.StatusUpdateRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "Em preparação"
                }
            }
        },
        "presenters.AcompanhamentoDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "pedidos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.PedidoDTO"
                    }
                },
                "tempoEstimado": {
                    "description": "in minutes",
                    "type": "integer"
                }
            }
        },
        "presenters.ClienteDTO": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "presenters.ItemPedidoDTO": {
            "type": "object",
            "properties": {
                "nomeProduto": {
                    "type": "string"
                },
                "precoUnitario": {
                    "type": "number"
                },
                "produtoId": {
                    "type": "integer"
                },
                "quantidade": {
                    "type": "integer"
                },
                "subtotal": {
                    "type": "number"
                }
            }
        },
        "presenters.PedidoDTO": {
            "type": "object",
            "properties": {
                "cliente": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "identificacao": {
                    "type": "string"
                },
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenters.ItemPedidoDTO"
                    }
                },
                "status": {
                    "$ref": "#/definitions/entities.StatusPedido"
                },
                "tempoEstimado": {
                    "$ref": "#/definitions/time.Duration"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "presenters.ProdutoDTO": {
            "type": "object",
            "properties": {
                "categoria": {
                    "$ref": "#/definitions/entities.CatProduto"
                },
                "descricao": {
                    "type": "string"
                },
                "identificacao": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "number"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "sql.NullString": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lanchonete API - Tech Challenge 2",
	Description:      "API para o Tech Challenge 2 da FIAP - SOAT",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
